"base_url": "https://practice.expandtesting.com/notes/app"
"api_url": "https://practice.expandtesting.com/notes/api"
"email": "swethagandham2003@gmail.com"
"password": "Swetha@2003"
"timeout": 15
"performance_threshold": 1.5
"ui_login_threshold": 30